### PR TITLE
Update saxon9he.jar to version 9.9.1.7

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
This updates to the next minor version which is considered to be the most stable and reliable version by the upstream maintainers, so it should be save.

**Comment by stweil** [comment]
@zuphilip, do you know how to debug the CI failure for ci/dockercloud? I get error 404 when I want to see the details of that failure.

**Comment by stweil** [comment]
> do you know how to debug the CI failure for ci/dockercloud

The failure was caused by the unsupported `python` entry in `Dockerfile` and is fixed now.

**Comment by stweil** [comment]
The fix for `Dockerfile` requires also replacing `python2` by `python3` in `script/validate/hocr`. It was used for `hocr-spec-python` which should work with Python 3, too.

**Comment by stweil** [comment]
The update from Python 2 to Python 3 is not only needed to fix `docker build`, but also required in the OCR-D context.

**Review by kba — APPROVED** [review]
LGTM

**Pull request merged**
