### PR TITLE
:arrow_up: Upgrade to new version of hOCR-to-ALTO

### PR DESCRIPTION
**Pull request by zuphilip**
This solves #95 and #81 also no special features of ALTO 3.0 or ALTO 4.0 are considered in the transformations, but this would be anyways something for upstream.

### CODE REVIEW

**Comment by stweil** [comment]
Should be still provide the conversion from alto2.0 / alto2.1 to hocr (even if it is no longer needed) to be backward compatible? Removing it before release `1.0.0` would violate semantic versioning.

**Comment by zuphilip** [comment]
So you mean to do some other symlinking for these names of the transformations? Well, it would be easy to do but I am not sure whether it is needed. My feeling is also that releasing v1.0.0 might be soon now (merging PRs + testing should suffice IMO now). Maybe we can merge first the other PRs and then see how to proceed here. Okay? Or do you think we should first release a v0.3.0?

**Comment by stweil** [comment]
I suggest indeed to keep (modified) symlinks for those two transformations until a 1.0.0 is released.

**Comment by stweil** [comment]
Making a 0.3.0 as kind of pre-release for 1.0.0 would allow a longer test phase.

**Comment by zuphilip** [comment]
Please have a look at the new version.

**Comment by stweil** [comment]
https://digi.bib.uni-mannheim.de/ocr-fileformat/ now uses the new code.

**Pull request merged**
