### PR TITLE
update hocr2alto to include filak/hOCR-to-ALTO#23

### PR DESCRIPTION
**Pull request by kba**

### CODE REVIEW

**Comment by kba** [comment]
@stweil can this be merged?

**Review by stweil — APPROVED** [review]
Thank you.

**Comment by stweil** [comment]
> @stweil can this be merged?

Yes, I merged it now. Should we also tag a new release (0.4.1 or 0.5.0)?

**Comment by kba** [comment]
> Yes, I merged it now. Should we also tag a new release (0.4.1 or 0.5.0)?

Thanks! Since the new release will include both the JPageConverter update and the XSLT update, I'd say `0.5.0`.

**Pull request merged**
