### PR TITLE
Update Makefile for new version hocr-to-ALTO 1.3.2

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by stweil** [comment]
Thank you, Philipp.

**Comment by zuphilip** [comment]
That was a little too fast. I tested the Docker image only now and we have now:

ocr-transforms-codes

Let us see how to fix this...

**Comment by zuphilip** [comment]
I think these are the relevant lines: https://github.com/UB-Mannheim/ocr-fileformat/blob/master/lib.sh#L49-L52 . (However, I still don't have a comfortable testing environment here...)

**Comment by zuphilip** [comment]
Okay, it looks like all files are executable there:
```
bash-4.3# stat xslt/codes_lookup.xml
  File: 'xslt/codes_lookup.xml' -> '../vendor/hOCR-to-ALTO/codes_lookup.xml'
  Size: 39              Blocks: 0          IO Block: 4096   symbolic link
Device: 21h/33d Inode: 199         Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
```

**Comment by zuphilip** [comment]
We could use `realpath` to change that, i.e.
```
bash-4.3# realpath xslt/codes_lookup.xml | xargs stat
  File: /usr/local/share/ocr-fileformat/vendor/hOCR-to-ALTO/codes_lookup.xml
  Size: 11657           Blocks: 24         IO Block: 4096   regular file
Device: 21h/33d Inode: 342         Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
```
Is this a standard approach here?

**Comment by zuphilip** [comment]
(I moved the comments here in a new issue.)

**Pull request merged**
