### PR TITLE
Prepare new release

### PR DESCRIPTION
**Pull request by zuphilip**
See #29

### CODE REVIEW

**Comment by zuphilip** [comment]
@kba I think this is ready. Can we release it?

**Comment by kba** [comment]
Looks good, just needs to rebased against current master so the to-text transformations are actually available.

**Comment by stweil** [comment]
@kba, no need for a rebase, merge knows how to handle this.

**Comment by kba** [comment]
BTW: You can create release zip/tar.gz with `make release`. I've added them to the release.

**Pull request merged**
