### PR TITLE
Add PAGE XML examples

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by stweil** [comment]
Nice, thank you.

**Comment by stweil** [comment]
I updated the [website](https://digi.bib.uni-mannheim.de/ocr-fileformat/#help) and also fixed a [W3C validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdigi.bib.uni-mannheim.de%2Focr-fileformat%2F) warning.

**Comment by zuphilip** [comment]
Thank you! Do you know why the transformation abbyy__hocr is not showing up?

**Comment by stweil** [comment]
Yes, the xsl file was missing. I had to run `make all`, too. Done now.

**Pull request merged**
