### PR TITLE
Fix several html issues for the web interface

### PR DESCRIPTION
**Pull request by stweil**
This fixes all issues reported by the W3C validator.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
See [buggy](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdigi.bib.uni-mannheim.de%2Focr-fileformat%2F) and [fixed](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdigi.bib.uni-mannheim.de%2Focr-fileformat-test%2F) version.

**Comment by zuphilip** [comment]
(I don't see any bug which is solved by this.)

**Comment by stweil** [comment]
Nor do I. At least Firefox accepts the buggy HTML (nearly) without complaining. You can see some bugs marked red when looking at the HTML source in Firefox. The full list of bugs is shown by the W3C validator (see links in my previous comment).

**Comment by zuphilip** [comment]
Thank you @stweil !

**Pull request merged**
