### PR TITLE
Add abbyy2hocr transformation by @OCR-D

### PR DESCRIPTION
**Pull request by zuphilip**
I did not yet test it, but it looks straightforward.

### CODE REVIEW

**Comment by kba** [comment]
> Maybe including it in ocr-fileformat will increase the visibility of the transformation so that those shortcomings can be remedied.

Can you open issues at https://github.com/OCR-D/format-converters/issues lest we forget @jmechnich? Thank you

**Comment by zuphilip** [comment]
@kba Yes, thank you for the suggestion. That is what we discussed last Friday and I said that I will do that. We also discussed that at least the required parameters should be make optional for the integration here, because otherwise it might not be possible to use that in the GUI.

**Comment by zuphilip** [comment]
Here is a PR for making the parameters optional: https://github.com/OCR-D/format-converters/pull/8

**Comment by zuphilip** [comment]
The upstream PR is merged now. @jmechnich Can you test the new version where the parameters are not mandatory anymore? Is this now giving results in the GUI?

**Comment by jmechnich** [comment]
Upstream is already broken by another commit. :)
Actually, maybe we should consider using git submodules or a specific commit for the vendor packages as this is not the first time sth like this happened.

**Comment by zuphilip** [comment]
Here is PR for fixing the newly introduced regressions https://github.com/OCR-D/format-converters/pull/11

BTW I would love to see also some tests integrated with CI in the upstream repo.

**Comment by zuphilip** [comment]
Okay, upstream is merged now again. @jmechnich Can you give it a try again? :pray:

**Pull request merged**
