### PR TITLE
Move navbar above tab panes in web interface

### PR DESCRIPTION
**Pull request by zuphilip**
Previous:

navbar-now

With this PR:

navbar-move

### CODE REVIEW

**Comment by stweil** [comment]
While improving the look-and-feel: displaying the release tag might also be a good idea. Maybe at the right side of the black bar?

**Comment by zuphilip** [comment]
Agree on this idea. But I am not skilled enough to read the info automatically into this html.  Any help?

**Comment by zuphilip** [comment]
Or maybe just postpone it as an issue?

**Comment by kba** [comment]
Getting revision info into the web assets would require a build step or reliance on convention or installation. Not hard but finicky and nothing to do with this PR IIUC.

I liked the tabs as they were, but not enough to oppose this :)

**Comment by zuphilip** [comment]
( I prefer to click from top-to-bottom and left-to-right :)

**Pull request merged**
