### PR TITLE
update JPAGEViewer to 1.5.04

### PR DESCRIPTION
**Pull request by kba**
Better diagnostics and fixes some coordinate issues, c.f. https://github.com/PRImA-Research-Lab/prima-page-converter/issues/16 / https://github.com/PRImA-Research-Lab/prima-page-converter/commit/85102556b86ad746a7fe6fcacbde180c5c2aeb81

### CODE REVIEW

**Review by stweil — APPROVED** [review]
Thanks.

**Comment by kba** [comment]
@stweil do you want to make a new release or can I update ocrd_fileformat with current master?

**Comment by stweil** [comment]
@kba, would you mind if I fix the last commit message and do a forced push? s/JPAGEViewer/JPageConverter/

**Comment by kba** [comment]
> @kba, would you mind if I fix the last commit message and do a forced push? s/JPAGEViewer/JPageConverter/

oops, sure go ahead.

**Comment by stweil** [comment]
Done. New release: v0.4.0 = master.

**Pull request merged**
