### PR TITLE
update textract2page (v 0.2 - full LAYOUT etc.)

### PR DESCRIPTION
**Pull request by bertsky**
also needed techically since the older version still depdended on ocrd_utils (which we don't release anymore)

### CODE REVIEW

**Comment by bertsky** [comment]
I don't understand how the conflict emerges. I just wanted to update that submodule...

**Comment by bertsky** [comment]
Ah, forgot to fetch upstream.

**Comment by stweil** [comment]
Thanks!

**Comment by stweil** [comment]
@bertsky, I think that before a new release of ocrd_fileformat with this commit is released, we should have a solution for issue #185.

**Pull request merged**
