### PR TITLE
update textract2page, hOCR-to-ALTO and alto-schema

### PR DESCRIPTION
**Pull request by kba**

### CODE REVIEW

**Comment by stweil** [comment]
Why is this PR in draft mode?

**Comment by kba** [comment]
> Why is this PR in draft mode?

Because I intended to include the table support in textract2page but it is not merged yet, cf. https://github.com/UB-Mannheim/ocr-fileformat/pull/166#issuecomment-1708684176

But you're right, there's no reason not to merge anyway.

**Review by stweil — APPROVED** [review]
Thank you.

**Comment by stweil** [comment]
@kba, the updated hOCR-to-ALTO breaks the conversion from hOCR to ALTO because hocr__alto.xsl is now required and was missing. That is fixed in PR #167.

**Pull request merged**
